# Generated by Django 3.1 on 2020-08-14 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_post', models.CharField(max_length=200, verbose_name='Título do Post')),
                ('nome_autor', models.CharField(max_length=50, verbose_name='Nome do Autor')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
            ],
        ),
    ]
