# Generated by Django 3.1 on 2020-08-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_autor',
            field=models.EmailField(default=None, max_length=50, verbose_name='E-mail para contato com Autor'),
        ),
        migrations.AddField(
            model_name='post',
            name='postagem',
            field=models.TextField(default=None, max_length=500, verbose_name='Postagem'),
        ),
    ]
