# Generated by Django 3.1 on 2020-08-21 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título do Post')),
                ('conteudo', models.TextField(max_length=200, verbose_name='Conteúdo do Post')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autor.autor', verbose_name='Autor')),
            ],
        ),
    ]
