# Generated by Django 3.1 on 2020-08-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Publicação'),
        ),
    ]
